// MOCK: Replace with real JuegoService when /api/juegos 401 bug is fixed
import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { JuegoExtended } from '../models/juego-extended.interface';

@Injectable({
  providedIn: 'root'
})
export class MockJuegosService {

  private readonly juegos: JuegoExtended[] = [
    {
      id: 1,
      nombre: 'Catan',
      minJugadores: 3,
      maxJugadores: 4,
      duracionMediaMin: 90,
      complejidad: 'MEDIA',
      genero: 'ESTRATEGIA',
      idioma: 'MULTI',
      descripcion: 'Coloniza la isla de Catan recolectando recursos y construyendo caminos, poblados y ciudades. Negocia con otros jugadores para obtener los materiales que necesitas. El primer jugador en alcanzar 10 puntos de victoria gana la partida.',
      ubicacion: 'A1',
      recomendadoDosJugadores: false,
      activo: true,
      imagenUrl: 'assets/images/juegos/catan.jpg',
      edadMinima: 10,
      editorial: 'Devir',
      rating: 4.5,
      totalRatings: 142,
      tags: ['colonizacion', 'negociacion', 'recursos', 'clasico']
    },
    {
      id: 2,
      nombre: 'Carcassonne',
      minJugadores: 2,
      maxJugadores: 5,
      duracionMediaMin: 35,
      complejidad: 'BAJA',
      genero: 'ESTRATEGIA',
      idioma: 'MULTI',
      descripcion: 'Construye el paisaje medieval de Carcassonne colocando losetas de terreno y posicionando tus seguidores como caballeros, monjes o ladrones. Cada turno amplias el mapa y decides estrategicamente donde colocar a tus peones para maximizar puntos.',
      ubicacion: 'A2',
      recomendadoDosJugadores: true,
      activo: true,
      imagenUrl: 'assets/images/juegos/carcassonne.jpg',
      edadMinima: 7,
      editorial: 'Devir',
      rating: 4.4,
      totalRatings: 118,
      tags: ['losetas', 'medieval', 'colocacion']
    },
    {
      id: 3,
      nombre: 'Dixit',
      minJugadores: 3,
      maxJugadores: 8,
      duracionMediaMin: 30,
      complejidad: 'BAJA',
      genero: 'FAMILIAR',
      idioma: 'MULTI',
      descripcion: 'Un juego de creatividad e imaginacion donde los jugadores deben dar pistas sobre sus cartas ilustradas. Las evocadoras ilustraciones permiten multiples interpretaciones, y el reto esta en ser lo suficientemente ambiguo para que no todos adivinen tu carta.',
      ubicacion: 'A3',
      recomendadoDosJugadores: false,
      activo: true,
      imagenUrl: 'assets/images/juegos/dixit.jpg',
      edadMinima: 8,
      editorial: 'Libellud',
      rating: 4.3,
      totalRatings: 95,
      tags: ['creatividad', 'ilustraciones', 'familiar']
    },
    {
      id: 4,
      nombre: 'Virus!',
      minJugadores: 2,
      maxJugadores: 6,
      duracionMediaMin: 20,
      complejidad: 'BAJA',
      genero: 'CARTAS',
      idioma: 'ESPANOL',
      descripcion: 'Un juego de cartas rapido y divertido donde compites por ser el primero en completar un cuerpo sano. Usa virus para infectar a tus rivales y medicinas para curar tus propios organos. Cuidado con las cartas de tratamiento que pueden cambiar el rumbo de la partida.',
      ubicacion: 'A4',
      recomendadoDosJugadores: true,
      activo: true,
      imagenUrl: 'assets/images/juegos/virus.jpg',
      edadMinima: 8,
      editorial: 'Tranjis Games',
      rating: 4.1,
      totalRatings: 130,
      tags: ['rapido', 'familiar', 'cartas']
    },
    {
      id: 5,
      nombre: 'Dobble',
      minJugadores: 2,
      maxJugadores: 8,
      duracionMediaMin: 15,
      complejidad: 'BAJA',
      genero: 'PARTY',
      idioma: 'MULTI',
      descripcion: 'Un juego de rapidez visual donde cada par de cartas comparte exactamente un simbolo en comun. Se el mas rapido en encontrar el simbolo compartido entre tu carta y la del centro. Incluye cinco minijuegos diferentes para variar la experiencia.',
      ubicacion: 'A5',
      recomendadoDosJugadores: true,
      activo: true,
      imagenUrl: 'assets/images/juegos/dobble.jpg',
      edadMinima: 6,
      editorial: 'Asmodee',
      rating: 4.0,
      totalRatings: 110,
      tags: ['rapidez', 'visual', 'party']
    },
    {
      id: 6,
      nombre: 'Azul',
      minJugadores: 2,
      maxJugadores: 4,
      duracionMediaMin: 35,
      complejidad: 'MEDIA',
      genero: 'ABSTRACTO',
      idioma: 'MULTI',
      descripcion: 'Inspirado en los azulejos decorativos del Palacio Real de Evora, los jugadores compiten por crear los mosaicos mas bellos. Selecciona fichas de las fabricas compartidas y colocatas en tu tablero personal, pero cuidado con las fichas sobrantes que restan puntos.',
      ubicacion: 'A6',
      recomendadoDosJugadores: true,
      activo: true,
      imagenUrl: 'assets/images/juegos/azul.jpg',
      edadMinima: 8,
      editorial: 'Next Move Games',
      rating: 4.6,
      totalRatings: 88,
      tags: ['abstracto', 'mosaico', 'patron']
    },
    {
      id: 7,
      nombre: '7 Wonders',
      minJugadores: 2,
      maxJugadores: 7,
      duracionMediaMin: 30,
      complejidad: 'MEDIA',
      genero: 'ESTRATEGIA',
      idioma: 'MULTI',
      descripcion: 'Lidera una de las siete grandes ciudades del mundo antiguo y construye tu maravilla a lo largo de tres eras. Mediante un mecanismo de draft de cartas, desarrolla tu civilizacion en ciencia, comercio, militar o civil para alcanzar la gloria eterna.',
      ubicacion: 'A7',
      recomendadoDosJugadores: false,
      activo: true,
      imagenUrl: 'assets/images/juegos/7wonders.jpg',
      edadMinima: 10,
      editorial: 'Repos Production',
      rating: 4.5,
      totalRatings: 102,
      tags: ['civilizacion', 'draft', 'simultaneo']
    },
    {
      id: 8,
      nombre: 'Ticket to Ride Europa',
      minJugadores: 2,
      maxJugadores: 5,
      duracionMediaMin: 45,
      complejidad: 'BAJA',
      genero: 'FAMILIAR',
      idioma: 'MULTI',
      descripcion: 'Viaja a traves de Europa construyendo rutas ferroviarias entre ciudades iconicas. Colecciona cartas de vagones para reclamar rutas y completa tus billetes de destino para ganar puntos. Incluye estaciones, tuneles y ferris que anaden variedad estrategica.',
      ubicacion: 'B1',
      recomendadoDosJugadores: true,
      activo: true,
      imagenUrl: 'assets/images/juegos/ticket-to-ride.jpg',
      edadMinima: 8,
      editorial: 'Days of Wonder',
      rating: 4.4,
      totalRatings: 125,
      tags: ['trenes', 'rutas', 'europa', 'familiar']
    },
    {
      id: 9,
      nombre: 'Pandemic',
      minJugadores: 2,
      maxJugadores: 4,
      duracionMediaMin: 45,
      complejidad: 'MEDIA',
      genero: 'COOPERATIVO',
      idioma: 'MULTI',
      descripcion: 'Trabaja en equipo como especialistas de enfermedades para detener cuatro epidemias letales antes de que se extiendan por todo el planeta. Cada jugador tiene un rol unico y debeis coordinar vuestras acciones para encontrar las curas a tiempo.',
      ubicacion: 'B2',
      recomendadoDosJugadores: true,
      activo: true,
      imagenUrl: 'assets/images/juegos/pandemic.jpg',
      edadMinima: 8,
      editorial: 'Z-Man Games',
      rating: 4.5,
      totalRatings: 98,
      tags: ['cooperativo', 'enfermedades', 'equipo']
    },
    {
      id: 10,
      nombre: 'Codigo Secreto',
      minJugadores: 4,
      maxJugadores: 8,
      duracionMediaMin: 15,
      complejidad: 'BAJA',
      genero: 'PARTY',
      idioma: 'ESPANOL',
      descripcion: 'Dos equipos rivales compiten por contactar con sus agentes secretos a traves de palabras clave. Los jefes de espias dan pistas de una sola palabra que pueden relacionar varias cartas, pero cuidado con la carta del asesino que acaba la partida al instante.',
      ubicacion: 'B3',
      recomendadoDosJugadores: false,
      activo: true,
      imagenUrl: 'assets/images/juegos/codigo-secreto.jpg',
      edadMinima: 14,
      editorial: 'Devir',
      rating: 4.3,
      totalRatings: 85,
      tags: ['palabras', 'equipos', 'espias', 'party']
    },
    {
      id: 11,
      nombre: 'Exploding Kittens',
      minJugadores: 2,
      maxJugadores: 5,
      duracionMediaMin: 15,
      complejidad: 'BAJA',
      genero: 'CARTAS',
      idioma: 'MULTI',
      descripcion: 'Un juego de cartas absurdo y divertido donde los jugadores roban cartas hasta que alguien roba un gatito explosivo y queda eliminado. Usa cartas de accion como desactivaciones, ataques y barajadas para sobrevivir el mayor tiempo posible.',
      ubicacion: 'B4',
      recomendadoDosJugadores: true,
      activo: true,
      imagenUrl: 'assets/images/juegos/exploding-kittens.jpg',
      edadMinima: 7,
      editorial: 'Exploding Kittens LLC',
      rating: 3.8,
      totalRatings: 105,
      tags: ['humor', 'eliminacion', 'rapido']
    },
    {
      id: 12,
      nombre: 'King of Tokyo',
      minJugadores: 2,
      maxJugadores: 6,
      duracionMediaMin: 30,
      complejidad: 'BAJA',
      genero: 'DADOS',
      idioma: 'MULTI',
      descripcion: 'Controla a un monstruo gigante que lucha por conquistar Tokyo. Lanza dados para atacar, curarte, ganar energia o sumar puntos de victoria. Decide cuando entrar o salir de Tokyo en este emocionante juego de dados con tematica kaiju.',
      ubicacion: 'B5',
      recomendadoDosJugadores: false,
      activo: true,
      imagenUrl: 'assets/images/juegos/king-of-tokyo.jpg',
      edadMinima: 8,
      editorial: 'Iello',
      rating: 4.1,
      totalRatings: 78,
      tags: ['monstruos', 'dados', 'combate']
    },
    {
      id: 13,
      nombre: 'Mysterium',
      minJugadores: 2,
      maxJugadores: 7,
      duracionMediaMin: 42,
      complejidad: 'MEDIA',
      genero: 'COOPERATIVO',
      idioma: 'MULTI',
      descripcion: 'Un fantasma intenta comunicar a los mediums quienes son los sospechosos, las ubicaciones y las armas del crimen mediante cartas de vision oniricas. Los mediums deben interpretar las abstractas imagenes para resolver el misterio antes de que amanezca.',
      ubicacion: 'B6',
      recomendadoDosJugadores: false,
      activo: true,
      imagenUrl: 'assets/images/juegos/mysterium.jpg',
      edadMinima: 10,
      editorial: 'Libellud',
      rating: 4.3,
      totalRatings: 72,
      tags: ['misterio', 'cooperativo', 'deduccion']
    },
    {
      id: 14,
      nombre: 'Splendor',
      minJugadores: 2,
      maxJugadores: 4,
      duracionMediaMin: 30,
      complejidad: 'MEDIA',
      genero: 'ESTRATEGIA',
      idioma: 'MULTI',
      descripcion: 'Conviertete en un mercader del Renacimiento coleccionando gemas para adquirir minas, transportes y artesanos. Cada carta comprada reduce el coste de futuras adquisiciones, creando un motor economico que te acerca a la victoria con 15 puntos de prestigio.',
      ubicacion: 'B7',
      recomendadoDosJugadores: true,
      activo: true,
      imagenUrl: 'assets/images/juegos/splendor.jpg',
      edadMinima: 10,
      editorial: 'Space Cowboys',
      rating: 4.4,
      totalRatings: 91,
      tags: ['gemas', 'motor', 'renacimiento']
    },
    {
      id: 15,
      nombre: 'Terraforming Mars',
      minJugadores: 1,
      maxJugadores: 5,
      duracionMediaMin: 120,
      complejidad: 'ALTA',
      genero: 'ESTRATEGIA',
      idioma: 'MULTI',
      descripcion: 'Dirige una corporacion dedicada a terraformar Marte elevando la temperatura, el nivel de oxigeno y creando oceanos. Gestiona cientos de proyectos unicos que representan avances tecnologicos, desde la introduccion de microorganismos hasta impactar asteroides contra el planeta.',
      ubicacion: 'C1',
      recomendadoDosJugadores: true,
      activo: true,
      imagenUrl: 'assets/images/juegos/terraforming-mars.jpg',
      edadMinima: 12,
      editorial: 'FryxGames',
      rating: 4.8,
      totalRatings: 115,
      tags: ['ciencia-ficcion', 'motor', 'corporaciones', 'marte']
    },
    {
      id: 16,
      nombre: 'Wingspan',
      minJugadores: 1,
      maxJugadores: 5,
      duracionMediaMin: 55,
      complejidad: 'MEDIA',
      genero: 'ESTRATEGIA',
      idioma: 'MULTI',
      descripcion: 'Un juego de motor de cartas donde los jugadores son entusiastas de las aves que buscan atraer las mejores especies a sus reservas naturales. Cada ave proporciona habilidades unicas que se combinan creando potentes cadenas de acciones en tres habitats distintos.',
      ubicacion: 'C2',
      recomendadoDosJugadores: true,
      activo: true,
      imagenUrl: 'assets/images/juegos/wingspan.jpg',
      edadMinima: 10,
      editorial: 'Stonemaier Games',
      rating: 4.7,
      totalRatings: 108,
      tags: ['aves', 'motor', 'naturaleza']
    },
    {
      id: 17,
      nombre: 'Gloomhaven',
      minJugadores: 1,
      maxJugadores: 4,
      duracionMediaMin: 120,
      complejidad: 'ALTA',
      genero: 'ROL',
      idioma: 'INGLES',
      descripcion: 'Una epica aventura cooperativa de combate tactico en un mundo de fantasia oscura. Con una campana de mas de 90 escenarios, los jugadores controlan mercenarios que exploran mazmorras, toman decisiones narrativas y desbloquean nuevas clases a lo largo de cientos de horas de juego.',
      ubicacion: 'C3',
      recomendadoDosJugadores: true,
      activo: true,
      imagenUrl: 'assets/images/juegos/gloomhaven.jpg',
      edadMinima: 14,
      editorial: 'Cephalofair Games',
      rating: 4.9,
      totalRatings: 65,
      tags: ['campana', 'mazmorra', 'tactico', 'legacy']
    },
    {
      id: 18,
      nombre: 'Scythe',
      minJugadores: 1,
      maxJugadores: 5,
      duracionMediaMin: 100,
      complejidad: 'ALTA',
      genero: 'ESTRATEGIA',
      idioma: 'MULTI',
      descripcion: 'En una Europa alternativa de los anos 1920 con mechs gigantes, lidera una faccion compitiendo por conquistar territorios, alistar reclutas, producir recursos y construir estructuras. Cada faccion tiene habilidades unicas en este juego de estrategia asimetrica con un motor economico profundo.',
      ubicacion: 'C4',
      recomendadoDosJugadores: true,
      activo: true,
      imagenUrl: 'assets/images/juegos/scythe.jpg',
      edadMinima: 14,
      editorial: 'Stonemaier Games',
      rating: 4.7,
      totalRatings: 82,
      tags: ['mechs', 'area-control', 'asimetrico', 'motor']
    },
    {
      id: 19,
      nombre: 'Uno',
      minJugadores: 2,
      maxJugadores: 10,
      duracionMediaMin: 30,
      complejidad: 'BAJA',
      genero: 'CARTAS',
      idioma: 'MULTI',
      descripcion: 'El clasico juego de cartas donde los jugadores deben deshacerse de todas sus cartas combinando colores o numeros. Las cartas de accion como Roba 2, Cambio de sentido y Comodin anaden emocion. No olvides gritar UNO cuando te quede una sola carta.',
      ubicacion: 'C5',
      recomendadoDosJugadores: true,
      activo: true,
      imagenUrl: 'assets/images/juegos/uno.jpg',
      edadMinima: 7,
      editorial: 'Mattel',
      rating: 3.6,
      totalRatings: 150,
      tags: ['clasico', 'familiar', 'rapido']
    },
    {
      id: 20,
      nombre: 'Jenga',
      minJugadores: 1,
      maxJugadores: 8,
      duracionMediaMin: 20,
      complejidad: 'BAJA',
      genero: 'PARTY',
      idioma: 'MULTI',
      descripcion: 'El icono de los juegos de habilidad donde los jugadores retiran bloques de madera de una torre y los colocan en la parte superior. La tension aumenta con cada turno a medida que la estructura se vuelve mas inestable. Pierde quien derrumbe la torre.',
      ubicacion: 'C6',
      recomendadoDosJugadores: true,
      activo: true,
      imagenUrl: 'assets/images/juegos/jenga.jpg',
      edadMinima: 6,
      editorial: 'Hasbro',
      rating: 3.5,
      totalRatings: 135,
      tags: ['destreza', 'torre', 'party']
    },
    {
      id: 21,
      nombre: 'Monopoly',
      minJugadores: 2,
      maxJugadores: 8,
      duracionMediaMin: 120,
      complejidad: 'BAJA',
      genero: 'FAMILIAR',
      idioma: 'ESPANOL',
      descripcion: 'El juego de mesa mas famoso del mundo donde compras propiedades, construyes casas y hoteles, y cobras alquiler a tus rivales. Gestiona tu dinero sabiamente mientras recorres el tablero y negocias tratos con otros jugadores para dominar el mercado inmobiliario.',
      ubicacion: 'C7',
      recomendadoDosJugadores: false,
      activo: true,
      imagenUrl: 'assets/images/juegos/monopoly.jpg',
      edadMinima: 8,
      editorial: 'Hasbro',
      rating: 3.5,
      totalRatings: 148,
      tags: ['clasico', 'economico', 'propiedades']
    },
    {
      id: 22,
      nombre: 'Risk',
      minJugadores: 2,
      maxJugadores: 6,
      duracionMediaMin: 120,
      complejidad: 'MEDIA',
      genero: 'ESTRATEGIA',
      idioma: 'ESPANOL',
      descripcion: 'El clasico juego de estrategia militar donde los jugadores despliegan ejercitos por el mapa mundial para conquistar territorios y continentes. Forma alianzas, planifica ataques y defiende tus posiciones con tiradas de dados en este eterno juego de dominacion global.',
      ubicacion: 'D1',
      recomendadoDosJugadores: false,
      activo: true,
      imagenUrl: 'assets/images/juegos/risk.jpg',
      edadMinima: 10,
      editorial: 'Hasbro',
      rating: 3.7,
      totalRatings: 120,
      tags: ['militar', 'conquista', 'clasico']
    },
    {
      id: 23,
      nombre: 'Trivial Pursuit',
      minJugadores: 2,
      maxJugadores: 6,
      duracionMediaMin: 60,
      complejidad: 'BAJA',
      genero: 'PARTY',
      idioma: 'ESPANOL',
      descripcion: 'Pon a prueba tu conocimiento general en seis categorias: Geografia, Entretenimiento, Historia, Arte y Literatura, Ciencia y Naturaleza, y Deportes. Recorre el tablero respondiendo preguntas para recolectar los seis quesitos y ganar la partida.',
      ubicacion: 'D2',
      recomendadoDosJugadores: false,
      activo: true,
      imagenUrl: 'assets/images/juegos/trivial-pursuit.jpg',
      edadMinima: 12,
      editorial: 'Hasbro',
      rating: 3.6,
      totalRatings: 95,
      tags: ['trivia', 'conocimiento', 'clasico']
    },
    {
      id: 24,
      nombre: 'Lobo Hombre de Castronegro',
      minJugadores: 8,
      maxJugadores: 18,
      duracionMediaMin: 30,
      complejidad: 'BAJA',
      genero: 'DEDUCCION',
      idioma: 'ESPANOL',
      descripcion: 'Cada noche los hombres lobo devoran a un aldeano, y cada dia los aldeanos votan para eliminar a un sospechoso. Con roles especiales como la vidente, la bruja y el cazador, los aldeanos intentan descubrir quienes son los lobos antes de que sea demasiado tarde.',
      ubicacion: 'D3',
      recomendadoDosJugadores: false,
      activo: true,
      imagenUrl: 'assets/images/juegos/lobo-castronegro.jpg',
      edadMinima: 10,
      editorial: 'Asmodee',
      rating: 4.0,
      totalRatings: 88,
      tags: ['roles-ocultos', 'social', 'grupos-grandes']
    },
    {
      id: 25,
      nombre: 'La Resistencia',
      minJugadores: 5,
      maxJugadores: 10,
      duracionMediaMin: 30,
      complejidad: 'BAJA',
      genero: 'DEDUCCION',
      idioma: 'ESPANOL',
      descripcion: 'En un futuro distopico, la resistencia lucha contra el gobierno. Pero entre los rebeldes se esconden espias infiltrados. Los jugadores debaten, acusan y votan para decidir quien participa en las misiones, mientras los traidores intentan sabotearlas sin ser descubiertos.',
      ubicacion: 'D4',
      recomendadoDosJugadores: false,
      activo: true,
      imagenUrl: 'assets/images/juegos/la-resistencia.jpg',
      edadMinima: 13,
      editorial: 'Indie Boards & Cards',
      rating: 4.1,
      totalRatings: 62,
      tags: ['traidor', 'social', 'votacion']
    },
    {
      id: 26,
      nombre: 'Catapulta de Queso',
      minJugadores: 2,
      maxJugadores: 4,
      duracionMediaMin: 15,
      complejidad: 'BAJA',
      genero: 'PARTY',
      idioma: 'ESPANOL',
      descripcion: 'Un alocado juego de destreza donde los jugadores lanzan trozos de queso con catapultas intentando acertar en las rebanadas de pan. La mecanica de catapulta es simple pero adictiva, y las risas estan garantizadas en cada lanzamiento fallido.',
      ubicacion: 'D5',
      recomendadoDosJugadores: true,
      activo: true,
      imagenUrl: 'assets/images/juegos/catapulta-queso.jpg',
      edadMinima: 6,
      editorial: 'Blue Orange',
      rating: 3.7,
      totalRatings: 28,
      tags: ['destreza', 'humor', 'infantil']
    },
    {
      id: 27,
      nombre: 'Arkham Horror LCG',
      minJugadores: 1,
      maxJugadores: 2,
      duracionMediaMin: 90,
      complejidad: 'ALTA',
      genero: 'COOPERATIVO',
      idioma: 'ESPANOL',
      descripcion: 'Sumérgete en los mitos de Lovecraft en este juego de cartas cooperativo con campanas narrativas. Construye tu mazo de investigador, explora localizaciones siniestras y enfrentate a horrores cosmicos mientras resuelves misterios cada vez mas peligrosos.',
      ubicacion: 'D6',
      recomendadoDosJugadores: true,
      activo: true,
      imagenUrl: 'assets/images/juegos/arkham-horror-lcg.jpg',
      edadMinima: 14,
      editorial: 'Fantasy Flight Games',
      rating: 4.7,
      totalRatings: 55,
      tags: ['lovecraft', 'campana', 'construccion-mazo', 'narrativo']
    },
    {
      id: 28,
      nombre: 'Root',
      minJugadores: 2,
      maxJugadores: 4,
      duracionMediaMin: 75,
      complejidad: 'ALTA',
      genero: 'ESTRATEGIA',
      idioma: 'MULTI',
      descripcion: 'Un juego de guerra asimetrico ambientado en un bosque encantador donde cuatro facciones animales luchan por el dominio. Cada faccion juega de forma completamente diferente: los gatos marcan territorio, las aguilas conquistan, la alianza forestal recluta y el vagabundo explora.',
      ubicacion: 'D7',
      recomendadoDosJugadores: false,
      activo: true,
      imagenUrl: 'assets/images/juegos/root.jpg',
      edadMinima: 10,
      editorial: 'Leder Games',
      rating: 4.6,
      totalRatings: 58,
      tags: ['asimetrico', 'area-control', 'animales']
    },
    {
      id: 29,
      nombre: 'Patchwork',
      minJugadores: 2,
      maxJugadores: 2,
      duracionMediaMin: 22,
      complejidad: 'MEDIA',
      genero: 'ABSTRACTO',
      idioma: 'MULTI',
      descripcion: 'Un elegante juego para dos donde los jugadores compiten por construir la colcha de retazos mas estetica y funcional. Compra parches de tela con botones y tiempo, encajandolos en tu tablero personal. Cada hueco vacio al final resta puntos.',
      ubicacion: 'E1',
      recomendadoDosJugadores: true,
      activo: true,
      imagenUrl: 'assets/images/juegos/patchwork.jpg',
      edadMinima: 8,
      editorial: 'Lookout Games',
      rating: 4.5,
      totalRatings: 74,
      tags: ['dos-jugadores', 'puzzle', 'abstracto']
    },
    {
      id: 30,
      nombre: 'Jaipur',
      minJugadores: 2,
      maxJugadores: 2,
      duracionMediaMin: 30,
      complejidad: 'BAJA',
      genero: 'CARTAS',
      idioma: 'MULTI',
      descripcion: 'Dos mercaderes rivales compiten en los mercados de Jaipur por el titulo de comerciante personal del Maharaja. Intercambia y vende mercancias como telas, especias y oro, buscando el momento perfecto para vender mientras los precios son altos.',
      ubicacion: 'E2',
      recomendadoDosJugadores: true,
      activo: true,
      imagenUrl: 'assets/images/juegos/jaipur.jpg',
      edadMinima: 10,
      editorial: 'Space Cowboys',
      rating: 4.4,
      totalRatings: 68,
      tags: ['dos-jugadores', 'comercio', 'mercado']
    },
    {
      id: 31,
      nombre: 'Hanabi',
      minJugadores: 2,
      maxJugadores: 5,
      duracionMediaMin: 25,
      complejidad: 'MEDIA',
      genero: 'COOPERATIVO',
      idioma: 'MULTI',
      descripcion: 'Un juego cooperativo unico donde los jugadores sostienen sus cartas al reves, viendo solo las cartas de los demas. Mediante pistas limitadas, debeis crear juntos un espectaculo pirotecnico perfecto colocando cartas de cinco colores en orden ascendente.',
      ubicacion: 'E3',
      recomendadoDosJugadores: true,
      activo: true,
      imagenUrl: 'assets/images/juegos/hanabi.jpg',
      edadMinima: 8,
      editorial: 'Cocktail Games',
      rating: 4.2,
      totalRatings: 52,
      tags: ['cooperativo', 'memoria', 'comunicacion-limitada']
    },
    {
      id: 32,
      nombre: 'Sushi Go',
      minJugadores: 2,
      maxJugadores: 5,
      duracionMediaMin: 15,
      complejidad: 'BAJA',
      genero: 'CARTAS',
      idioma: 'MULTI',
      descripcion: 'Un adorable juego de draft de cartas con tematica de sushi. Elige una carta de tu mano y pasa el resto al siguiente jugador, intentando crear las mejores combinaciones de nigiri, maki, tempura y sashimi. Tres rondas rapidas para coronar al mejor comensal.',
      ubicacion: 'E4',
      recomendadoDosJugadores: true,
      activo: true,
      imagenUrl: 'assets/images/juegos/sushi-go.jpg',
      edadMinima: 8,
      editorial: 'Gamewright',
      rating: 4.1,
      totalRatings: 83,
      tags: ['draft', 'sushi', 'rapido']
    },
    {
      id: 33,
      nombre: 'Saboteur',
      minJugadores: 3,
      maxJugadores: 10,
      duracionMediaMin: 30,
      complejidad: 'BAJA',
      genero: 'DEDUCCION',
      idioma: 'MULTI',
      descripcion: 'Los enanos mineros cavan tuneles en busca de oro, pero entre ellos se esconden saboteadores que intentan impedir que lleguen al tesoro. Coloca cartas de tunel para abrir camino o bloquearlo, y trata de descubrir quien trabaja en tu contra.',
      ubicacion: 'E5',
      recomendadoDosJugadores: false,
      activo: true,
      imagenUrl: 'assets/images/juegos/saboteur.jpg',
      edadMinima: 8,
      editorial: 'Amigo',
      rating: 3.9,
      totalRatings: 76,
      tags: ['traidor', 'mineria', 'tuneles']
    },
    {
      id: 34,
      nombre: 'Blokus',
      minJugadores: 2,
      maxJugadores: 4,
      duracionMediaMin: 25,
      complejidad: 'BAJA',
      genero: 'ABSTRACTO',
      idioma: 'MULTI',
      descripcion: 'Un juego abstracto de estrategia territorial donde cada jugador coloca piezas de colores tipo tetris en el tablero. Cada nueva pieza debe tocar al menos una esquina de tus piezas anteriores pero nunca un lado. Gana quien coloque mas piezas.',
      ubicacion: 'E6',
      recomendadoDosJugadores: true,
      activo: true,
      imagenUrl: 'assets/images/juegos/blokus.jpg',
      edadMinima: 7,
      editorial: 'Mattel',
      rating: 4.0,
      totalRatings: 69,
      tags: ['abstracto', 'territorial', 'puzzle']
    },
    {
      id: 35,
      nombre: 'Dungeons & Dragons Starter',
      minJugadores: 2,
      maxJugadores: 6,
      duracionMediaMin: 180,
      complejidad: 'ALTA',
      genero: 'ROL',
      idioma: 'ESPANOL',
      descripcion: 'La caja de inicio perfecta para adentrarse en el juego de rol mas famoso del mundo. Incluye reglas simplificadas, personajes pregenerados y una aventura completa que guia tanto a jugadores novatos como al director de juego a traves de mazmorras, dragones y epicas historias de fantasia.',
      ubicacion: 'E7',
      recomendadoDosJugadores: false,
      activo: true,
      imagenUrl: 'assets/images/juegos/dnd-starter.jpg',
      edadMinima: 12,
      editorial: 'Wizards of the Coast',
      rating: 4.6,
      totalRatings: 45,
      tags: ['rol', 'fantasia', 'narrativo', 'campana']
    }
  ];

  getAll(): Observable<JuegoExtended[]> {
    return of(this.juegos);
  }

  getById(id: number): Observable<JuegoExtended | undefined> {
    return of(this.juegos.find(j => j.id === id));
  }

  getByGenero(genero: string): Observable<JuegoExtended[]> {
    return of(this.juegos.filter(j => j.genero === genero));
  }

  getFeatured(): Observable<JuegoExtended[]> {
    const sorted = [...this.juegos].sort((a, b) => (b.rating ?? 0) - (a.rating ?? 0));
    return of(sorted.slice(0, 6));
  }

  search(term: string): Observable<JuegoExtended[]> {
    const lower = term.toLowerCase();
    return of(
      this.juegos.filter(j =>
        j.nombre.toLowerCase().includes(lower) ||
        j.genero.toLowerCase().includes(lower) ||
        (j.tags ?? []).some(tag => tag.toLowerCase().includes(lower))
      )
    );
  }
}
